### ISSUE TITLE
Compatible iPhone app?

### ISSUE THREAD

**Issue by Roycinger** [o-fl0w/stash-vr#10]
Hi,

As DeoVR and HereSphere are not available for iPhone, is there a way to use stash-vr with an iPhone?
Thanks!

**Comment by o-fl0w** [comment]
Stash-VR currently acts as a middleware only, serving players such as DeoVR and HereSphere with data from a Stash server. No built-in UI except for the status page.

What's your use case? Do you want to browse your content from a phone? (but as you probably know that can be done straight from Stash already)

**Comment by Roycinger** [comment]
> 

Thanks for getting back!
My use case is to pop my phone (an iPhone in this case) in one of those cheaper VR headsets and watch VR content on it.
I understood the usecase of stash-vr but I read in the documentation that it's only compatible with DeoVR and HereSphere.
Hence I'm asking if my usecase is able to be covered with another app which I'm not aware of and is somehow also supported outside those 2 apps mentioned above.

**Comment by o-fl0w** [comment]
I see, kind of like google cardboard I presume.

I'm not very familiar with that space but if you can find an app like DeoVR/HS for iPhone (preferrable one that also has an app for regular VR headsets) that has an open protocol we could have a look.

Another option depending on your needs is to find a media player app for iPhone which also supports VR and simply browse your files through your local network/DLNA (without using stash or stash-vr) - perhaps VLC can do that?
