### ISSUE TITLE
No thumbnail displays if you don't have heatmaps on videos with funscripts

### ISSUE THREAD

**Issue by SilentSpartan** [o-fl0w/stash-vr#16]
If your video has a funscript associated with it, but you do not have heatmaps generated, it results by not displaying any thumbnail at all (won't see the video previews either). 

It would be nice if no heatmap is found on a interactive video, it falls back to using the default cover.

**Comment by o-fl0w** [comment]
fixed in https://github.com/o-fl0w/stash-vr/commit/c704758b6d6c4b85ac590ba39da962794ee4a79c
