### ISSUE TITLE
No scrubbing for VR videos in Heresphere

### ISSUE THREAD

**Issue by slabking** [o-fl0w/stash-vr#18]
Just checking to see if this is me, or if this happens to anyone else. Stash 0.22.1, Stash-VR 0.6.0. Running this on Unraid, via Docker.

When I visit my Stash-VR instance in Heresphere, I can play both flat and VR videos. Everything works fine, except for VR videos - I can't skip forward in the video using the control sticks, and I can't select a point in the video scrubber to move to another point. When I do that, the video just stops playing altogether, and I need to select a different video before anything will play.

Flat videos work OK - I can skip forward, select a different time, etc. Only VR videos have this limitation.

Is this something that's only happening on my end? Has anyone seen anything like this?

Thanks!

**Comment by nerfdaderp** [comment]
I'm have different issues but the issue sounds familiar. If you can, check the encoding setting in Heresphere. It's in the main default view, second row. I've had that setting somehow change on me in the past and it caused all kinds of problems with VR videos. Hopefully thats your problem

**Comment by slabking** [comment]
Thanks, I'll give it a shot!

**Comment by slabking** [comment]
That was it, thanks! I had to switch Heresphere from `transcoding` to `direct`. Thanks again for the help!

Leaving this issue open in case this is something Stash-VR can handle, but if not, no worries about closing this.

**Comment by o-fl0w** [comment]
Last I checked HereSphere will continue use whatever mode is selected, i.e. if you select transcoding then the next video will also use that mode until you change it back to direct.
