### ISSUE TITLE
Connections over HTTPS instead of HTTP

### ISSUE THREAD

**Issue by sharklazerwallo** [o-fl0w/stash-vr#2]
**Issue**: When using stash-vr behind a reverse proxy that forces HTTPS, I'm able to connect to it initially but all metadata that is returned appears to be hardcoded to use HTTP (I believe that it's being done [here ](https://github.com/o-fl0w/stash-vr/blob/f842cfc7dac35e6178f7b88cbb6d0383df7205ec/internal/api/heresphere/http.go#L20)and [here](https://github.com/o-fl0w/stash-vr/blob/f842cfc7dac35e6178f7b88cbb6d0383df7205ec/internal/api/deovr/http.go#L18) but please correct me if I'm wrong, Go is definitely not my expertise). Using HereSphere, it does not follow the HTTP-to-HTTPS redirect and instead just keeps issuing the requests.

Is it possible to provide an option to allow these URLs to respond with HTTPS? I was able to work around this by opting this specific domain out of the forced redirect but generally prefer operating everything over HTTPS. Thanks again for a great and easy to setup otherwise option to handle VR streaming, was by far the easiest to get going outside of this.

**Comment by o-fl0w** [comment]
I admire the fact you went for a workaround and I agree - everything https should definitely be possible. Thank you for reporting this.

I've pushed a [fix](https://github.com/o-fl0w/stash-vr/pull/3) available now from [v0.3.15](https://github.com/o-fl0w/stash-vr/releases/tag/v0.3.15), hopefully this will solve your issue. Please report back if it doesn't and I'll have another look.

**Comment by o-fl0w** [comment]
Just did a test and it didn't seem to solve the issue. Sorry about that. I'll have another look. 
If you happened to try it out, let me know if it worked for you.

**Comment by o-fl0w** [comment]
New fix out now with v0.3.17
It should detect if you're behind a reverse proxy and use https accordingly. Try updating and running without any extra configuration first. If you still have issues you could force https by setting env. var. `FORCE_HTTPS="true"`. Hope this helps.
