### ISSUE TITLE
How to find filter id?

### ISSUE THREAD

**Issue by milindpatel63** [o-fl0w/stash-vr#21]
I created a new filter in stash, but i have to specify a id here in stash-vr. How do i get the id for the filter i created in stash?
Is there any wat of specifying filter via names?

**Comment by o-fl0w** [comment]
I'll look into specifying filters via names but until then you can browse to http://_staship_:9999/playground and in there paste and run the following query 
`{
  findSavedFilters {
    id
    name
  }
}`

**Comment by o-fl0w** [comment]
If you have an empty `FILTERS` env and `LOG_LEVEL=debug` you'll also get the filter names and ids in the log.
