### ISSUE TITLE
"Cannot query field \\\"rating\\\"

### ISSUE THREAD

**Issue by GoldstarZV** [o-fl0w/stash-vr#24]
I got stash-vr running, but when I browse to it in heresphere, I have no thumbnails on any scenes, and when I click on any of them they don't play.

In docker logs, I get spammed heaps with:

`
ERR build error="FindSceneFull: returned error 422 Unprocessable Entity: {\"errors\":[{\"message\":\"Cannot query field \\\"rating\\\" on type \\\"Studio\\\". Did you mean \\\"rating100\\\"?\",\"locations\":[{\"line\":31,\"column\":3}],\"extensions\":{\"code\":\"GRAPHQL_VALIDATION_FAILED\"}},{\"message\":\"Cannot query field \\\"rating\\\" on type \\\"Performer\\\". Did you mean \\\"rating100\\\"?\",\"locations\":[{\"line\":45,\"column\":3}],\"extensions\":{\"code\":\"GRAPHQL_VALIDATION_FAILED\"}},{\"message\":\"Cannot query field \\\"rating\\\" on type \\\"Studio\\\". Did you mean \\\"rating100\\\"?\",\"locations\":[{\"line\":31,\"column\":3}],\"extensions\":{\"code\":\"GRAPHQL_VALIDATION_FAILED\"}},{\"message\":\"Cannot query field \\\"rating\\\" on type \\\"Performer\\\". Did you mean \\\"rating100\\\"?\",\"locations\":[{\"line\":45,\"column\":3}],\"extensions\":{\"code\":\"GRAPHQL_VALIDATION_FAILED\"}},{\"message\":\"Cannot query field \\\"rating\\\" on type \\\"Studio\\\". Did you mean \\\"rating100\\\"?\",\"locations\":[{\"line\":31,\"column\":3}],\"extensions\":{\"code\":\"GRAPHQL_VALIDATION_FAILED\"}},{\"message\":\"Cannot query field \\\"rating\\\" on type \\\"Performer\\\". Did you mean \\\"rating100\\\"?\",\"locations\":[{\"line\":45,\"column\":3}],\"extensions\":{\"code\":\"GRAPHQL_VALIDATION_FAILED\"}}],\"data\":null}" mod=heresphere route=videoData videoId=5914
`

Pulled the latest image as of today, and running latest commit on stash develop branch

**Comment by o-fl0w** [comment]
Fixed in 4c1b4ace17c159faecda84bdce33525877aac3a3
