### ISSUE TITLE
Scenes not showing up in HereSphere when Stash has no saved filters

### ISSUE THREAD

**Issue by BollywoodMaster** [o-fl0w/stash-vr#4]
Looks like this for me:
Terminal:
![image](https://user-images.githubusercontent.com/106441871/194690023-41045bb6-93a6-40f8-bea2-f91a38fba8ef.png)

![image](https://user-images.githubusercontent.com/106441871/194690123-731698d0-08a4-4dc7-8d23-03ca8e14806c.png)

What did i miss in the setup process?

**Comment by o-fl0w** [comment]
Do you have the default filters only on Stash front page? Like "Recently released" etc. They won't be picked up by Stash-VR https://github.com/o-fl0w/stash-vr#unsupported-filter-types

Create your own custom filter and save them (you can easily reproduce the default ones from the front page) and they should be picked up.

**Comment by o-fl0w** [comment]
Or you can update to latest Stash-VR if you don't want to create filters in Stash. Latest version will add a default section containing all scenes.

https://github.com/o-fl0w/stash-vr/releases/tag/v0.3.26
