### ISSUE TITLE
Support for multi-file scenes

### ISSUE THREAD

**Issue by Kruk2** [o-fl0w/stash-vr#6]
Latest version of stash added option to link multiple files to one scene.
This is especially handy for JAV video which often come in several parts.
Stream sources could include all files linked to a video.

Question:
https://github.com/o-fl0w/stash-vr/blob/1f85132c0fee6f84143ee29dfc8466909f08543d/internal/api/heresphere/videodata.go#L165
Do we actually need to set all possible stream sources that stash offers? I'm always playing direct stream.
If we populate stream sources with multiple files and multiple resolutions then the list might be too big.
Maybe for each file linked to a scene include direct stream + highest resolution stash offers?

**Comment by philpw99** [comment]
The multi-file feature for scenes is not for JAV. 
If you have JAV, you should use one movie with several scenes. Stash has native support for JAV scenes. You can specify which scene is 1st in the  movie, which one is 2nd...
Multi-file is for the same video with different resolution or codec. In case one file cannot be played, the player can try the next file, then next ...etc.

**Comment by Kruk2** [comment]
Possibly.
But I found that multi-files work much better for my use cases:
1. I can assign all jav parts to one scene. Then use scraper on it, assign performers, assign scene code, tag it etc. In short: I have only one scene to maintain.
2. It was super easy to add multi-files feature to stash-vr as it already supports scenes. Adding support for movies would be more challenging.  What's worse, heresphere doesn't support it anyway so pretending that parts are just different version of the same movie is the only solution for now.

From what I can see "multi-part scenes" are still considered a valid feature so movies are not the real solution.
https://github.com/stashapp/stash/issues/2276

**Comment by justwjx** [comment]
totally agree, a essential request!
